-- Generated by node scripts/generate-database-seed.mjs from the unchanged frontend fixtures.
-- Demo snapshot: April 22, 2026. Replay skips existing IDs; clean reset reproduces exact data.
-- No profiles/Auth users, fake media, fake coordinates, or visible tag assignments are seeded.
begin;
insert into public.farms (id, name, timezone, created_at, updated_at) values
  ('00000000-0000-4000-8000-000000000001', 'Bays Ranch', 'America/Los_Angeles', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

insert into public.employees (id, farm_id, full_name, active, created_at, updated_at) values
  ('10000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', 'Isaac Wang', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'Maya Patel', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', 'Liam Johnson', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001', 'Sophia Lee', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000001', 'Alex Rivera', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000006', '00000000-0000-4000-8000-000000000001', 'Anthony Wells', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000007', '00000000-0000-4000-8000-000000000001', 'Grace Chen', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000008', '00000000-0000-4000-8000-000000000001', 'Noah Davis', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000009', '00000000-0000-4000-8000-000000000001', 'Olivia Martin', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000010', '00000000-0000-4000-8000-000000000001', 'Lucas Reed', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000011', '00000000-0000-4000-8000-000000000001', 'Amelia Torres', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('10000000-0000-4000-8000-000000000012', '00000000-0000-4000-8000-000000000001', 'Ben Wilson', true, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

insert into public.fields (id, farm_id, name, latitude, longitude, created_at, updated_at) values
  ('30000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', 'FIELD A', null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('30000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', 'FIELD B', null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('30000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', 'FIELD C', null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('30000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001', 'FIELD D', null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

insert into public.activity_logs (id, farm_id, employee_id, field_id, activity_type, activity_date, started_at, ended_at, summary, response_accuracy, review_status, created_at, updated_at) values
  ('20000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000001', '30000000-0000-4000-8000-000000000001', 'Spraying', '2026-04-19', '2026-04-19T06:00:00-07:00', '2026-04-19T10:40:00-07:00', 'Offline guided voice log created at 2026-04-08T22:01:01.711Z. Question (activity_type): What type of activity was this — spraying, fertilizing, planting, irrigating, harvesting, scouting, pruning, soil work, or equipment maintenance? Answer: I''m leaving first, I''m going to go home. Question (field_block): Where were you working (field, block, or area)? Answer: yes, in one part and then 130 and 200 yes, and 130 for uh 160 and no, this yes no, no, uhm no no I remember, uhm uhm uhm, no, I don''t remember anything.', 90, 'pending', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('20000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000002', '30000000-0000-4000-8000-000000000002', 'Harvesting', '2026-04-20', '2026-04-20T07:30:00-07:00', '2026-04-20T11:15:00-07:00', 'Harvested the mature crop in Field B from 7:30 AM to 11:15 AM. Completed the north and central rows, moved the harvested bins to the collection area, and flagged the remaining south rows for the next pass.', 90, 'pending', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('20000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000003', '30000000-0000-4000-8000-000000000003', 'Planting', '2026-04-21', '2026-04-21T08:00:00-07:00', '2026-04-21T12:00:00-07:00', 'Planted the prepared rows in Field C from 8:00 AM to noon. Checked seed spacing and planting depth before starting, completed the scheduled section, and cleaned the planter after the final pass.', 90, 'pending', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('20000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000004', '30000000-0000-4000-8000-000000000004', 'Irrigation', '2026-04-22', '2026-04-22T06:30:00-07:00', '2026-04-22T09:30:00-07:00', 'Ran the morning irrigation cycle in Field D from 6:30 AM to 9:30 AM. Checked line pressure, cleared two blocked emitters, and confirmed even coverage before shutting down the system.', 90, 'pending', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('20000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000001', '10000000-0000-4000-8000-000000000005', '30000000-0000-4000-8000-000000000001', 'Scouting', '2026-04-22', '2026-04-22T07:00:00-07:00', '2026-04-22T08:00:00-07:00', 'Walked Field A to check crop condition and irrigation coverage. No new issues were reported. This recording has already been approved and is excluded from the original four-row design preview.', 90, 'approved', '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

insert into public.recordings (id, farm_id, activity_log_id, recorded_at, is_new, storage_bucket, storage_path, duration_seconds, created_at, updated_at) values
  ('40000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000001', '2026-04-22T10:00:00-07:00', false, null, null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('40000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000002', '2026-04-22T10:05:00-07:00', false, null, null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('40000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000003', '2026-04-22T10:10:00-07:00', false, null, null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('40000000-0000-4000-8000-000000000004', '00000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000004', '2026-04-22T10:15:00-07:00', true, null, null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z'),
  ('40000000-0000-4000-8000-000000000005', '00000000-0000-4000-8000-000000000001', '20000000-0000-4000-8000-000000000005', '2026-04-22T10:20:00-07:00', false, null, null, null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

insert into public.tags (id, farm_id, name, created_by, created_at, updated_at) values
  ('50000000-0000-4000-8000-000000000001', '00000000-0000-4000-8000-000000000001', 'Needs Review', null, '2026-04-22T17:30:00Z', '2026-04-22T17:30:00Z')
on conflict (id) do nothing;

commit;
